notifications:
  slack: true
  email: false

sudo: required
language: python
python:
  - 2.7
  - 3.5

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -U pip wheel
  - pip install -U Cython
  - pip install -U tox-travis tox

script:
  - tox
